language: go

go: 1.3

before_install:
- export GOPATH=`pwd`/go

install:
- go get github.com/mattn/goveralls
- go get code.google.com/p/go.tools/cmd/cover
- go get -d -v ./...

script:
- go install -v github.com/mattn/goveralls
- go install -v github.com/modocache/gover
- go install -v gorcini
- ./run_tests.sh
- $GOPATH/bin/goveralls -coverprofile=coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN

env:
  global:
    secure: WJrIzIVMah9gB4sehqZIPcsV1CDJoSHXIyBYB3MgaV1pAUsy85wTNHTEarlkmApOcODkh1IZ07jQw89EZ7+kUi3IGZ3zQH5wdtK7AgIDKYLnHX7zSA7AqgP+756a/6VtcK4ejJlaY0zYgqGiUGnjklc37r6UBaBy2O4TLL0HR4s=
