language: go

go: 1.3

before_install:
- export GOPATH=`pwd`/go
- export TESTABLE_PKGS="common/resource common/server gorcini gorcini/resource gorcini/model"

install:
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- go get code.google.com/p/go.tools/cmd/cover
- go get -d -v ./...

script:
- go install -v github.com/mattn/goveralls
- go install -v gorcini
- for test in $TESTABLE_PKGS; do gocov test -v -covermode=count -coverprofile=profile $test >> coverage.gocov; done
- gocov report coverage.gocov > coverage.out
- $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

env:
  global:
    secure: WJrIzIVMah9gB4sehqZIPcsV1CDJoSHXIyBYB3MgaV1pAUsy85wTNHTEarlkmApOcODkh1IZ07jQw89EZ7+kUi3IGZ3zQH5wdtK7AgIDKYLnHX7zSA7AqgP+756a/6VtcK4ejJlaY0zYgqGiUGnjklc37r6UBaBy2O4TLL0HR4s=
