language: go

go: 1.3

before_install:
- export GOPATH=`pwd`/go
- export PKGS="common/resource common/server gorcini gorcini/resource gorcini/model"

install:
- for pkg in $PKGS; do go get -v $pkg; done
- go get -d -v ./...

script:
- for pkg in $PKGS; do go install -v $pkg; done
