language: go

go:
  1.3
  tip
  
before_install:
  - export GOPATH=`pwd`/go

install:
  - go get github.com/go-martini/martini
  - go get github.com/codegangsta/inject

  
script:
  - go test -v ./...
  - go install -v gorcini
